# Generated by Django 2.1.4 on 2018-12-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181227_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='consult_content',
            field=models.TextField(verbose_name='咨询内容'),
        ),
    ]
